cargo-features = ["per-package-target"]

[package]
name = "rustsbi-prototyper"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
forced-target = "riscv64imac-unknown-none-elf"

[dependencies]
log = "0.4.21"
panic-halt = "0.2.0"
riscv = "0.11.1"
rustsbi = { git = "https://github.com/rustsbi/rustsbi", features = ["machine"] }
spin = "0.9.8"
uart16550 = "0.0.1"

[[bin]]
name = "rustsbi-prototyper"
test = false
bench = false

[workspace]
members = ["xtask"]

[workspace.package]
edition = "2021"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/prototyper"

[profile.release]
debug = true
