[workspace]
resolver = "2"
members = [
  "prototyper",
  "test-kernel"
]

[workspace.package]
edition = "2021"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/prototyper"

[profile.release]
debug = true
