cargo-features = ["per-package-target"]

[package]
name = "rustsbi-prototyper"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
forced-target = "riscv64imac-unknown-none-elf"

[dependencies]
panic-halt = "0.2.0"

[[bin]]
name = "rustsbi-prototyper"
test = false
bench = false

[workspace]
members = ["xtask"]

[workspace.package]
edition = "2021"
license = "MulanPSL-2.0 OR MIT"
repository = "https://github.com/rustsbi/prototyper"

[profile.release]
debug = true
