[config]
default_to_workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.prototyper-build]
command = "cargo"
args = ["build", "-prustsbi-prototyper", "--release"]
dependencies = ["clean"]

[tasks.prototyper]
command = "rust-objcopy"
args = ["--binary-architecture=riscv64", "target/riscv64imac-unknown-none-elf/release/rustsbi-prototyper",
        "--output-target=binary", "target/riscv64imac-unknown-none-elf/release/rustsbi-prototyper.bin"
]
dependencies = ["prototyper-build"]
