[package]
name = "rustsbi-supervisor"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
naked-function = "0.1.5"
sbi-rt = "0.0.3"
rcore-console = "0.0.0"
uart16550 = "0.0.1"
